name: Build and deploy to Azure

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Setup python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: pip install -r requirements.txt

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}

      - name: Deploy to webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: atharvaacn-test-app
          package: .
